language: python
python:
  - 2.7

services: mysql

# addons:
#   apt:
#     packages: reportlab

virtualenv:
    system_site_packages: true

before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - sudo rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - sudo apt-get update -qq

# command to install dependencies
install:
  - sudo apt-get install python-reportlab

before_script:
  - 'python -c "from reportlab.pdfgen import canvas"'
  - 'echo $?'

  # create database and run script to create tables
  - 'mysql -e "create database testdb;"'
  - 'mysql testdb < web2py_auth_script.sql'
  # download web2py
  - 'wget http://web2py.com/examples/static/web2py_src.zip -O /tmp/web2py_src.zip'
  - 'unzip /tmp/web2py_src.zip'
  # copy application from github to applications/app_name
  - "mkdir web2py/applications/travis_example"
  - 'for file in "./"*; do [[ $file = ./web2py ]] && continue; cp -r "$file" "./web2py/applications/travis_example"; done'
  - 'cd web2py'

script: python web2py.py -S travis_example -M -R applications/travis_example/testRunner.py

# to use container-based infrastructure. Faster build setup
# change false to required to use sudo
# sudo: false